export const ADMIN_USERS_TEXT = {
  pageTitle: "User Management",
  pageDescription: "Manage gamer accounts, membership roles, access status, and activity signals.",
  backToHomePage: "Back to HomePage",
  searchPlaceholder: "Search username, display name, or email",
  role: "Role",
  status: "Status",
  verified: "Verified",
  allRoles: "All roles",
  allStatuses: "All statuses",
  allVerification: "All verification",
  active: "Active",
  inactive: "Inactive",
  emailVerified: "Verified",
  emailUnverified: "Unverified",
  user: "User",
  member: "Member",
  admin: "Admin",
  avatar: "Avatar",
  username: "Username",
  displayName: "Display name",
  email: "Email",
  posts: "Posts",
  createdAt: "Created",
  lastSeenAt: "Last seen",
  actions: "Actions",
  viewDetails: "View details",
  deactivate: "Deactivate",
  reactivate: "Reactivate",
  noUsers: "No users found",
  noUsersDescription: "Try another search or adjust the filters.",
  loadingUsers: "Loading users",
  usersCountSuffix: "users",
  statusUpdated: "Account status updated",
  roleUpdated: "Role updated",
  postManagement: "Post Management",
  marketplaceReview: "Marketplace Review",
  confirmDeactivateTitle: "Deactivate account",
  confirmDeactivateDescription: "This user will no longer be able to access active account features.",
  cancel: "Cancel",
  confirm: "Confirm",
  userDetails: "User details",
  profile: "Profile",
  bio: "Bio",
  noBio: "No bio provided.",
  followers: "Followers",
  following: "Following",
  marketplaceListings: "Marketplace listings",
  never: "Never",
  selfDeactivateBlocked: "You cannot deactivate your own admin account.",
  roleLocked: "Admin role is locked",
} as const;
