export const CONFIG = {
  MEMBERSHIP_PRICE: 99_000,
  MEMBERSHIP_DAYS: 30,
  COMMISSION_RATE: 0.05,
  POSTS_PER_PAGE: 20,
  MESSAGES_PER_PAGE: 50,
  MAX_FILE_SIZE_MB: 50,
  MAX_IMAGES_PER_POST: 6,
  USERNAME_MIN_LENGTH: 3,
  USERNAME_MAX_LENGTH: 20,
  BIO_MAX_LENGTH: 300,
} as const;
