export const ROUTES = {
  home: "/",
  login: "/login",
  register: "/register",
  feed: "/feed",
  explore: "/explore",
  saved: "/saved",
  notifications: "/notifications",
  post: (id: string) => `/posts/${id}`,
  marketplace: "/marketplace",
  listing: (id: string) => `/marketplace/${id}`,
  messages: "/messages",
  conversation: (id: string) => `/messages/${id}`,
  profile: (username: string) => `/profile/${username}`,
  settings: "/settings",
  membership: "/settings/membership",
  admin: "/admin",
  adminListings: "/admin/listings",
  adminUsers: "/admin/users",
} as const;
