export const ADMIN_POSTS_TEXT = {
  postsTitle: "Post Management",
  postsDescription: "Moderate regular posts and marketplace content from one console.",
  listingsTitle: "Marketplace Review",
  listingsDescription: "Review pending listings, inspect media, and approve or reject with context.",
  backToHomePage: "Back to HomePage",
  searchPlaceholder: "Search content, username, or game",
  postType: "Post type",
  status: "Status",
  listingStatus: "Listing status",
  all: "All",
  regular: "Regular",
  marketplace: "Marketplace",
  active: "Active",
  hidden: "Hidden",
  deleted: "Deleted",
  pending_review: "Pending",
  approved: "Approved",
  rejected: "Rejected",
  sold: "Sold",
  author: "Author",
  content: "Content",
  media: "Media",
  tags: "Tags",
  reactions: "Reactions",
  comments: "Comments",
  createdAt: "Created",
  actions: "Actions",
  viewDetails: "View details",
  hide: "Hide",
  softDelete: "Soft delete",
  approve: "Approve",
  reject: "Reject",
  noPosts: "No posts found",
  noPostsDescription: "Try another search or adjust filters.",
  loadingPosts: "Loading posts",
  postDetails: "Post details",
  mediaGallery: "Media gallery",
  listingInfo: "Listing info",
  rejectReason: "Reject reason",
  rejectReasonPlaceholder: "Explain why this listing is rejected",
  cancel: "Cancel",
  confirmReject: "Reject listing",
  statusUpdated: "Post status updated",
  listingReviewed: "Listing reviewed",
  noContent: "No content.",
  noTags: "No tags",
} as const;
